import { Product } from './product';

export const CATEGORIES = [
  { id: '10', name: 'Coffee Shop',   bg: '#F4ECE4', count: '20+ ITEMS', image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '1', name: 'Fresh Fruits',   bg: '#FFF0E6', count: '40+ ITEMS', image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '2', name: 'Vegetables',     bg: '#F0FFF4', count: '35+ ITEMS', image: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '3', name: 'Dairy & Eggs',   bg: '#FFFDE7', count: '25+ ITEMS', image: 'https://images.pexels.com/photos/1556704/pexels-photo-1556704.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '4', name: 'Meat & Poultry', bg: '#FFF0F0', count: '30+ ITEMS', image: 'https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '5', name: 'Bakery',         bg: '#FFF8F0', count: '20+ ITEMS', image: 'https://images.pexels.com/photos/1586444/pexels-photo-1586444.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '6', name: 'Snacks',         bg: '#F9F0FF', count: '50+ ITEMS', image: 'https://images.pexels.com/photos/1621939/pexels-photo-1621939.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '7', name: 'Beverages',      bg: '#E8F4FD', count: '45+ ITEMS', image: 'https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '8', name: 'Prepared Foods', bg: '#FFF4E5', count: '15+ ITEMS', image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=400' },
  { id: '9', name: 'Pantry',         bg: '#F5F5DC', count: '60+ ITEMS', image: 'https://images.pexels.com/photos/5953480/pexels-photo-5953480.jpeg?auto=compress&cs=tinysrgb&w=400' },
];

export const PRODUCTS: Product[] = [
  {
    id: '501',
    name: 'Vanilla Latte',
    price: 4.5,
    image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Smooth espresso with steamed milk and vanilla syrup.',
    category: 'Coffee Shop',
    rating: 4.9,
    deliveryTime: '5-10 min',
    ingredients: ['Espresso', 'Milk', 'Vanilla'],
  },
  {
    id: '11',
    name: 'Margherita Pizza',
    price: 12.5,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil.',
    category: 'Prepared Foods',
    rating: 4.8,
    deliveryTime: '15-20 min',
    ingredients: ['Dough', 'Tomato Sauce', 'Mozzarella', 'Basil'],
  },
  {
    id: '12',
    name: 'Classic Cheeseburger',
    price: 10.0,
    image: 'https://images.pexels.com/photos/1633525/pexels-photo-1633525.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy beef patty with cheddar cheese, lettuce, and tomato.',
    category: 'Prepared Foods',
    rating: 4.7,
    deliveryTime: '15-20 min',
    ingredients: ['Beef Bun', 'Cheese', 'Lettuce', 'Tomato'],
  },
  {
    id: '21',
    name: 'Ripe Hass Avocado',
    price: 5.5,
    image: 'https://images.pexels.com/photos/557659/pexels-photo-557659.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Creamy, ripe Hass avocado, perfect for toast or salad.',
    category: 'Fresh Fruits',
    rating: 4.9,
    deliveryTime: '5-10 min',
    ingredients: ['Avocado'],
  },
  {
    id: '1',
    name: 'Red Apples (1kg)',
    price: 4.5,
    image: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crispy and sweet organic red apples, harvested daily.',
    category: 'Fresh Fruits',
    rating: 4.8,
    deliveryTime: '15-20 min',
    ingredients: ['Apple'],
  },
  {
    id: '2',
    name: 'Fresh Milk (1L)',
    price: 3.2,
    image: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Pasteurized whole milk from local dairy farms.',
    category: 'Dairy & Eggs',
    rating: 4.9,
    deliveryTime: '10-15 min',
    ingredients: ['Milk'],
  },
  {
    id: '5',
    name: 'Croissant (4pcs)',
    price: 6.8,
    image: 'https://images.pexels.com/photos/1586444/pexels-photo-1586444.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Buttery and flaky French-style croissants, baked fresh.',
    category: 'Bakery',
    rating: 4.6,
    deliveryTime: '10-20 min',
    ingredients: ['Flour', 'Butter', 'Egg', 'Yeast'],
  },
  {
    id: '702',
    name: 'Matcha Green Tea',
    price: 5.2,
    image: 'https://images.pexels.com/photos/5946633/pexels-photo-5946633.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Premium ceremonial grade matcha tea.',
    category: 'Beverages',
    rating: 4.9,
    deliveryTime: '10-15 min',
    ingredients: ['Matcha Powder'],
  },
];
